<?php


?>
<script>
var users = <?php echo $this->getUsersJson(); ?>;

var loginSelect = new Element('select', { name: 'login[username]', id:'username' });
users.each(function(login){
    loginSelect.insert({bottom: new Element('option', { value: login['value'] }).update(login['label'])});
});

$('username').replace(loginSelect);
$('login').writeAttribute('type','hidden');
$('login').removeAttribute('class')
$('login').up().insert({bottom: new Element('span').update('This is just a demo ...')});
</script>